# -*- coding: utf-8 -*-
"""fase4-fiap-note7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBpxh_AwDbfrDIr9h41lvsOth25QIFjL

# Notebook 07: Modelagem de Machine Learning para Classificação Multiclasse

## Introdução

Este notebook é dedicado à etapa de **Modelagem de Machine Learning** do projeto, focando na resolução de um **problema de classificação multiclasse**. O contexto geral do projeto envolve a análise de dados relacionados à obesidade para compreender e classificar diferentes perfis de risco. A presente etapa visa desenvolver e avaliar modelos preditivos capazes de classificar instâncias em múltiplas categorias distintas de obesidade.

Este desafio de classificação multiclasse é crucial para identificar diferentes tipos de obesidade, permitindo intervenções mais direcionadas e eficazes. Este notebook estabelece uma relação direta com o **Notebook 06**, que foi integralmente dedicado às fases de Exploração de Dados (EDA) e Pré-processamento. Conforme estabelecido, o pipeline de pré-processamento, que incluiu tarefas como tratamento de valores ausentes, engenharia de atributos e padronização/normalização, foi previamente desenvolvido e validado. Portanto, neste ambiente, os dados já estão devidamente preparados para a fase de modelagem, utilizando o pipeline de pré-processamento previamente treinado.

Nosso foco principal neste notebook será a **comparação de múltiplos algoritmos de Machine Learning**. Serão implementados e treinados diversos modelos candidatos para abordar o problema de classificação multiclasse. A seleção desses algoritmos será guiada por sua adequação aos desafios do dataset e à natureza do problema.

Ao final deste processo de avaliação e comparação, será selecionado o **modelo oficial do projeto**. A decisão final será baseada em métricas de desempenho robustas e na capacidade do modelo de generalizar para dados não vistos, garantindo uma solução eficaz e confiável para o problema de classificação proposto.

## 1. Configuração do Ambiente

Esta seção é dedicada à configuração inicial do ambiente de desenvolvimento. Serão importadas as bibliotecas necessárias para as etapas subsequentes de manipulação de dados, visualização, modelagem de Machine Learning, avaliação de desempenho, otimização de hiperparâmetros e interpretação de modelos. A organização das importações visa facilitar a manutenção e a legibilidade do código.
"""

# 1.1. Importação de Bibliotecas Essenciais

# Manipulação de Dados
import pandas as pd
import numpy as np
import joblib # Para carregar o pipeline

# Visualização
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning - Modelos
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
# from sklearn.naive_bayes import GaussianNB # Não utilizada no dicionário de modelos inicial
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# Métricas de Avaliação
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix

# Validação Cruzada
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold

# Otimização de Hiperparâmetros
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

# SHAP (SHapley Additive exPlanations)
import shap

# Medição de Tempo
import time

# Outros utilitários
import warnings
warnings.filterwarnings('ignore')

"""## 2. Carregamento dos Dados e Reutilização do Pré-processador

Nesta etapa, a base de dados será carregada e preparada para a fase de modelagem. É crucial destacar que **o processo de pré-processamento não será recriado**. Em vez disso, será reutilizado **exatamente o mesmo pré-processador** que foi cuidadosamente desenvolvido e validado no `Notebook 06`. Esta abordagem garante que todos os algoritmos de Machine Learning que serão comparados neste notebook recebam os dados submetidos às mesmas transformações consistentes, eliminando qualquer viés introduzido por diferentes etapas de pré-processamento e assegurando uma comparação justa e equitativa do desempenho dos modelos. **Não será realizado nenhum `fit()` ou recriação de `ColumnTransformer` ou `Pipeline` nesta etapa.**
"""

# 2.1. Leitura da base de dados
df = pd.read_csv('Obesity.csv')

# 2.2. Separação entre X (features) e y (target)
# Utilizando iloc para selecionar a última coluna como y e as demais como X,
# garantindo a robustez contra variações no nome da coluna alvo.
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Adicionando as importações necessárias diretamente aqui para garantir sua disponibilidade
from sklearn.model_selection import train_test_split
import numpy as np
import joblib # Adicionado para resolver o NameError

# 2.3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 2.4. Codificação da variável alvo (y) para numérico
# Alguns modelos, como o XGBoost, exigem rótulos numéricos para classificação multiclasse.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)
y_encoded = le.transform(y)

# Substituir y_train, y_test e y pelos seus equivalentes codificados
y_train = y_train_encoded
y_test = y_test_encoded
y = y_encoded

print("Dados carregados e separados em conjuntos de treino e teste.")
print(f"Shape de X_train: {X_train.shape}")
print(f"Shape de X_test: {X_test.shape}")
print(f"Shape de y_train: {y_train.shape}")
print(f"Shape de y_test: {y_test.shape}")
print(f"Classes originais: {le.inverse_transform(np.unique(y))}")
print(f"Classes codificadas: {np.unique(y)}")

# 2.5. Carregamento e Extração do Pré-processador do Pipeline Salvo
# O arquivo 'pipeline_obesity_final.pkl' deve estar disponível no ambiente.
pipeline_salvo = joblib.load("pipeline_obesity_final.pkl")

# Extrair apenas o pré-processador do pipeline
preprocessor = pipeline_salvo.named_steps["preprocessor"]

print("\nPipeline de pré-processamento 'pipeline_obesity_final.pkl' carregado com sucesso.")
print(f"Pré-processador extraído: {preprocessor}")
print("O pré-processador está pronto para ser aplicado aos dados sem novo treinamento.")

"""## 3. Definição dos Modelos Candidatos

Nesta etapa, serão definidos os algoritmos de Machine Learning que serão avaliados para o problema de classificação multiclasse. Serão instanciados diversos modelos, abrangendo diferentes paradigmas de aprendizado. Para garantir a reprodutibilidade dos experimentos, um `random_state` fixo será aplicado aos algoritmos que o suportam. É fundamental ressaltar que **todos esses modelos utilizarão o mesmo pré-processador** (`preprocessor`) que foi extraído do `pipeline_obesity_final.pkl` no passo anterior. Isso garante que todas as transformações (padronização, one-hot encoding, etc.) serão aplicadas de forma consistente aos dados de entrada de cada modelo, permitindo uma comparação justa e direta de seus desempenhos.
"""

# 3.1. Definição do Dicionário de Modelos

modelos = {
    'Logistic Regression': LogisticRegression(random_state=42, solver='liblinear', multi_class='auto'),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'Extra Trees': ExtraTreesClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    'KNN': KNeighborsClassifier(),
    'SVM': SVC(random_state=42, probability=True), # probability=True para permitir predict_proba para ROC_AUC
    'XGBoost': XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss'),
    'LightGBM': LGBMClassifier(random_state=42, verbose=-1), # verbose=-1 para suprimir mensagens de aviso
    'CatBoost': CatBoostClassifier(random_state=42, verbose=0) # verbose=0 para não imprimir logs durante o treinamento
}

print("Modelos definidos com sucesso:")
for nome_modelo, modelo_obj in modelos.items():
    print(f"- {nome_modelo}: {modelo_obj.__class__.__name__}")

"""## 4. Avaliação Inicial dos Modelos Candidatos

Nesta seção, cada um dos modelos definidos será avaliado utilizando um pipeline que incorpora o pré-processador previamente extraído. O objetivo é obter uma primeira visão do desempenho de cada algoritmo em termos de métricas como Acurácia, Precisão, Recall e F1-Score (todas macro), além de uma avaliação por validação cruzada (`StratifiedKFold`) e o tempo de treinamento. Esta etapa é fundamental para a seleção dos modelos que prosseguirão para fases mais avançadas de otimização.
"""

from sklearn.pipeline import Pipeline

# Lista para armazenar os resultados de cada modelo
resultados = []

# Configuração para validação cruzada
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for nome_modelo, modelo_obj in modelos.items():
    print(f"\nAvaliando o modelo: {nome_modelo}")

    # Criação do Pipeline com pré-processador e classificador
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', modelo_obj)
    ])

    # Medir tempo de treinamento
    start_time = time.time()
    pipeline.fit(X_train, y_train)
    end_time = time.time()
    training_time = end_time - start_time

    # Previsões no conjunto de teste
    y_pred = pipeline.predict(X_test)

    # Cálculo das métricas
    accuracy = accuracy_score(y_test, y_pred)
    precision_macro = precision_score(y_test, y_pred, average='macro', zero_division=0)
    recall_macro = recall_score(y_test, y_pred, average='macro', zero_division=0)
    f1_macro = f1_score(y_test, y_pred, average='macro', zero_division=0)

    # Validação Cruzada (Cross-validation)
    # Usamos o pipeline para garantir que o pré-processamento seja aplicado em cada fold
    cv_scores = cross_val_score(pipeline, X, y, cv=kf, scoring='accuracy', n_jobs=-1) # usa X e y completos para CV
    cv_mean_accuracy = np.mean(cv_scores)

    # Armazenar resultados
    resultados.append({
        'Modelo': nome_modelo,
        'Acurácia': accuracy,
        'Precisão Macro': precision_macro,
        'Recall Macro': recall_macro,
        'F1 Macro': f1_macro,
        'CV Média Acurácia': cv_mean_accuracy,
        'Tempo de Treinamento (s)': training_time
    })

    print(f"  Acurácia: {accuracy:.4f}")
    print(f"  Precisão Macro: {precision_macro:.4f}")
    print(f"  Recall Macro: {recall_macro:.4f}")
    print(f"  F1 Macro: {f1_macro:.4f}")
    print(f"  CV Média Acurácia: {cv_mean_accuracy:.4f}")
    print(f"  Tempo de Treinamento: {training_time:.2f} segundos")

# Criar DataFrame com os resultados
df_resultados = pd.DataFrame(resultados)

# Exibir DataFrame, ordenando pela Acurácia CV para melhor visualização
df_resultados = df_resultados.sort_values(by='CV Média Acurácia', ascending=False).reset_index(drop=True)
display(df_resultados)

"""## 5. Comparação e Análise Inicial dos Modelos

Nesta seção, os resultados obtidos na avaliação inicial dos modelos são consolidados e visualizados para facilitar a comparação. A análise focará nas métricas de desempenho chave e no tempo de treinamento, com o objetivo de identificar os modelos mais promissores para otimização futura.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Ordenar o DataFrame por 'F1 Macro' para a comparação
df_resultados_ordenado = df_resultados.sort_values(by='F1 Macro', ascending=False).reset_index(drop=True)

print("### Tabela Consolidada de Resultados dos Modelos (Ordenada por F1 Macro)\n")
display(df_resultados_ordenado)

# --- Geração dos Gráficos de Comparação ---

def plot_metric(df, metric, title, ascending=False):
    plt.figure(figsize=(12, 6))
    sns.barplot(x='Modelo', y=metric, data=df.sort_values(by=metric, ascending=ascending))
    plt.title(title)
    plt.ylabel(metric)
    plt.xlabel('Modelo')
    plt.xticks(rotation=45, ha='right')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

# Gráfico de Acurácia
plot_metric(df_resultados_ordenado, 'Acurácia', 'Acurácia dos Modelos (Ordenado por F1 Macro)')

# Gráfico de Precisão Macro
plot_metric(df_resultados_ordenado, 'Precisão Macro', 'Precisão Macro dos Modelos (Ordenado por F1 Macro)')

# Gráfico de Recall Macro
plot_metric(df_resultados_ordenado, 'Recall Macro', 'Recall Macro dos Modelos (Ordenado por F1 Macro)')

# Gráfico de F1 Macro
plot_metric(df_resultados_ordenado, 'F1 Macro', 'F1 Macro dos Modelos (Ordenado por F1 Macro)')

# Gráfico de Tempo de Treinamento
plot_metric(df_resultados_ordenado, 'Tempo de Treinamento (s)', 'Tempo de Treinamento dos Modelos (Ordenado por F1 Macro)', ascending=True)

# Gráfico de Média da Cross Validation
plot_metric(df_resultados_ordenado, 'CV Média Acurácia', 'Média da Acurácia de Cross Validation dos Modelos (Ordenado por F1 Macro)')

"""### Análise Final e Seleção dos Modelos Finalistas

Com base na análise dos resultados obtidos na avaliação inicial dos modelos, considerando as métricas de desempenho chave e o tempo de treinamento, os modelos que se destacaram e serão selecionados para a próxima fase de otimização são:

#### Modelos Selecionados para Otimização:

1.  **CatBoost**
2.  **LightGBM**
3.  **XGBoost**

#### Justificativa Técnica da Escolha:

*   **F1 Macro**: Esta métrica é crucial para problemas de classificação multiclasse, especialmente quando há um possível desequilíbrio entre as classes. Os três modelos selecionados (CatBoost, LightGBM e XGBoost) consistentemente apresentaram as maiores pontuações de F1 Macro, indicando um excelente equilíbrio entre identificar corretamente as classes positivas e evitar falsos positivos.

*   **Acurácia**: Todos os três modelos demonstraram alta acurácia no conjunto de teste. CatBoost liderou, seguido por LightGBM e XGBoost, reforçando sua capacidade geral de fazer previsões corretas.

*   **CV Média Acurácia (Cross Validation Mean Accuracy)**: A média da acurácia obtida através da validação cruzada é um forte indicativo da capacidade de generalização do modelo. LightGBM e XGBoost apresentaram as maiores médias de acurácia na validação cruzada, sugerindo robustez e menor propensão a overfitting. CatBoost também obteve uma excelente pontuação.

*   **Tempo de Treinamento**: LightGBM e XGBoost se destacam por oferecerem um desempenho muito competitivo com tempos de treinamento significativamente menores, o que é valioso. Embora o CatBoost tenha um tempo de treinamento mais elevado, seu desempenho superior justifica sua inclusão entre os finalistas.

*   **Cross Validation Std (Desvio Padrão da Cross Validation)**: Embora esta métrica não estivesse disponível no `df_resultados` para análise quantitativa detalhada, a alta e consistente 'CV Média Acurácia' dos modelos selecionados já sugere uma boa estabilidade e consistência no desempenho entre os diferentes folds de validação cruzada.

Em resumo, CatBoost, LightGBM e XGBoost formam um conjunto sólido de modelos finalistas devido à sua performance consistentemente superior nas métricas de F1 Macro, Acurácia e capacidade de generalização demonstrada pela validação cruzada. A otimização de hiperparâmetros para esses modelos será o próximo passo para maximizar seu potencial.

## 6. Otimização dos Modelos Finalistas com `RandomizedSearchCV`

Nesta etapa, os três modelos selecionados na análise inicial (CatBoost, LightGBM e XGBoost) serão submetidos a um processo de otimização de hiperparâmetros utilizando `RandomizedSearchCV`. O objetivo é refinar o desempenho de cada modelo, buscando a melhor combinação de parâmetros dentro de um espaço de busca definido. Após a otimização, os modelos serão retreinados com os melhores parâmetros encontrados e suas métricas de desempenho serão recalculadas para uma nova comparação.
"""

from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold # Adicionei StratifiedKFold
from scipy.stats import uniform, randint
from sklearn.pipeline import Pipeline

# Added imports for the classifiers used in this cell
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

# Added imports for metrics and time
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import time

# Lista para armazenar os resultados dos modelos otimizados
resultados_otimizados = []

# Definição do kf para o RandomizedSearchCV com cv=3
kf_optimized = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# Modelos finalistas com seus parâmetros a serem otimizados
# Note que 'classifier__' é prefixado para os parâmetros dentro do pipeline
modelos_finalistas_params = {
    'CatBoost': {
        'model': CatBoostClassifier(random_state=42, verbose=0, allow_writing_files=False),
        'param_distributions': {
            'classifier__iterations': randint(100, 250), # Ajustado para 100-250
            'classifier__learning_rate': uniform(0.01, 0.14), # Ajustado para 0.01-0.15 (0.15-0.01=0.14)
            'classifier__depth': randint(4, 8), # Ajustado para 4-8
            'classifier__l2_leaf_reg': uniform(2, 6) # Ajustado para 2-8 (8-2=6)
        }
    },
    'LightGBM': {
        'model': LGBMClassifier(random_state=42, verbose=-1),
        'param_distributions': {
            'classifier__n_estimators': randint(100, 250), # Ajustado para 100-250
            'classifier__learning_rate': uniform(0.01, 0.14), # Ajustado para 0.01-0.15
            'classifier__num_leaves': randint(20, 50), # Ajustado para 20-50
            'classifier__max_depth': randint(3, 12), # Ajustado para 3-12
            'classifier__reg_alpha': uniform(0, 1),
            'classifier__reg_lambda': uniform(0, 1)
        }
    },
    'XGBoost': {
        'model': XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss'),
        'param_distributions': {
            'classifier__n_estimators': randint(100, 250), # Ajustado para 100-250
            'classifier__learning_rate': uniform(0.01, 0.14), # Ajustado para 0.01-0.15
            'classifier__max_depth': randint(3, 8), # Ajustado para 3-8
            'classifier__subsample': uniform(0.70, 0.30), # Ajustado para 0.70-1.00 (1.00-0.70=0.30)
            'classifier__colsample_bytree': uniform(0.70, 0.30) # Ajustado para 0.70-1.00
        }
    }
}

for nome_modelo, config in modelos_finalistas_params.items():
    print(f"\nOtimizando o modelo: {nome_modelo}")

    # Criação do Pipeline com pré-processador e classificador
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', config['model'])
    ])

    # Configuração do RandomizedSearchCV
    random_search = RandomizedSearchCV(
        estimator=pipeline,
        param_distributions=config['param_distributions'],
        n_iter=10, # Número de iterações, ajustado conforme solicitado
        cv=kf_optimized, # Utilizando o kf_optimized com n_splits=3
        scoring='f1_macro',
        random_state=42,
        n_jobs=-1, # Utilizar todos os cores disponíveis
        verbose=2, # Verbose ajustado para 2
        refit=True # Refit ajustado para True
    )

    # Medir tempo de treinamento do RandomizedSearchCV
    start_time = time.time()
    random_search.fit(X_train, y_train)
    end_time = time.time()
    training_time_optimization = end_time - start_time

    best_estimator = random_search.best_estimator_
    best_params = random_search.best_params_
    best_score_cv = random_search.best_score_ # Obtendo o best_score_ diretamente

    print(f"  Melhores parâmetros para {nome_modelo}: {best_params}")
    print(f"  Melhor F1 Macro (CV) para {nome_modelo}: {best_score_cv:.4f}")
    print(f"  Tempo de otimização para {nome_modelo}: {training_time_optimization:.2f} segundos")

    # Calcular métricas com o melhor estimador no conjunto de teste
    y_pred_optimized = best_estimator.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred_optimized)
    precision_macro = precision_score(y_test, y_pred_optimized, average='macro', zero_division=0)
    recall_macro = recall_score(y_test, y_pred_optimized, average='macro', zero_division=0)
    f1_macro = f1_score(y_test, y_pred_optimized, average='macro', zero_division=0)

    # Armazenar resultados otimizados
    resultados_otimizados.append({
        'Modelo Otimizado': nome_modelo,
        'Melhores Parâmetros': best_params,
        'Acurácia': accuracy,
        'Precisão Macro': precision_macro,
        'Recall Macro': recall_macro,
        'F1 Macro': f1_macro,
        'Best CV Score': best_score_cv, # Usando best_score_ diretamente
        'Tempo de Otimização (s)': training_time_optimization,
        'Best Estimator': best_estimator # Adicionando o best_estimator_ aqui
    })

    print(f"  Acurácia (Otimizado - Teste): {accuracy:.4f}")
    print(f"  Precisão Macro (Otimizado - Teste): {precision_macro:.4f}")
    print(f"  Recall Macro (Otimizado - Teste): {recall_macro:.4f}")
    print(f"  F1 Macro (Otimizado - Teste): {f1_macro:.4f}")

"""## 7. Nova Tabela Comparativa de Modelos Otimizados

A tabela a seguir apresenta os resultados dos modelos após o processo de otimização de hiperparâmetros, ordenados pela métrica F1 Macro. É possível observar o impacto da otimização no desempenho de cada modelo.
"""

import pandas as pd

# Criar DataFrame com os resultados otimizados
df_resultados_otimizados = pd.DataFrame(resultados_otimizados)

# Ordenar por F1 Macro para comparação
df_resultados_otimizados = df_resultados_otimizados.sort_values(by='F1 Macro', ascending=False).reset_index(drop=True)

print("### Tabela Comparativa de Resultados dos Modelos Otimizados (Ordenada por F1 Macro)\n")
display(df_resultados_otimizados)

# Gerar a interpretação técnica
print("\n### Interpretação Técnica da Otimização:\n")

# Encontrar o modelo com melhor F1 Macro após otimização (no conjunto de teste)
best_f1_model = df_resultados_otimizados.loc[df_resultados_otimizados['F1 Macro'].idxmax()]
print(f"- O modelo com o melhor desempenho (maior F1 Macro no conjunto de teste) após otimização é o **{best_f1_model['Modelo Otimizado']}** com F1 Macro de {best_f1_model['F1 Macro']:.4f}.")

# Comparar com os resultados iniciais (df_resultados)
# Certifique-se de que 'df_resultados' esteja disponível e contenha os resultados iniciais
# e que 'Modelo' seja a chave correta para o merge/lookup

# Renomear a coluna 'Modelo' para 'Modelo Otimizado' em df_resultados para facilitar a comparação
df_resultados_initial = df_resultados.rename(columns={'Modelo': 'Modelo Otimizado'})[['Modelo Otimizado', 'F1 Macro', 'Tempo de Treinamento (s)','CV Média Acurácia']]

# Mesclar os resultados iniciais e otimizados para fácil comparação
df_comparison = pd.merge(df_resultados_initial, df_resultados_otimizados, on='Modelo Otimizado', suffixes=('_initial', '_optimized'))

# Calcular ganho de desempenho para F1 Macro e CV Média Acurácia
df_comparison['Ganho F1 Macro'] = df_comparison['F1 Macro_optimized'] - df_comparison['F1 Macro_initial']
df_comparison['Ganho CV Acurácia'] = df_comparison['Best CV Score'] - df_comparison['CV Média Acurácia'] # Correção aplicada aqui

# Modelo com maior ganho de desempenho (F1 Macro)
max_gain_f1_model = df_comparison.loc[df_comparison['Ganho F1 Macro'].idxmax()]
print(f"- O modelo que apresentou o maior ganho de desempenho em **F1 Macro** foi o **{max_gain_f1_model['Modelo Otimizado']}** com um ganho de {max_gain_f1_model['Ganho F1 Macro']:.4f}.")

# Modelo que seguirá para a próxima etapa: o de melhor F1 Macro no teste, pois demonstra o melhor desempenho final
print(f"- Para a próxima etapa de interpretação (Feature Importance e SHAP), o modelo selecionado será o o **{best_f1_model['Modelo Otimizado']}**.")
print("  A justificativa é que ele demonstrou o melhor equilíbrio geral entre precisão e recall (F1 Macro) no conjunto de teste após a otimização, indicando ser o mais robusto para a tarefa de classificação.\n")

# Adicionar uma nota sobre os warnings do XGBoost e LightGBM, se aplicável
print("**Nota:** Durante a otimização, foram observados warnings para LightGBM e XGBoost relacionados ao uso de `feature names` e `use_label_encoder`. Estes são informativos e não impediram a execução ou a validade dos resultados da otimização. Para XGBoost, `use_label_encoder` é uma propriedade que foi descontinuada em versões mais recentes, e `eval_metric` é agora o método preferido para especificar a métrica de avaliação. Para LightGBM, o aviso sobre `feature names` geralmente ocorre quando o modelo é treinado em um DataFrame pandas com nomes de colunas e, em seguida, prevê em um array numpy sem eles, mas o pipeline aqui lida com isso de forma consistente.")

"""#### Nota sobre o Desvio Padrão da Cross Validation:

Conforme instruído, a análise foi realizada utilizando exclusivamente o DataFrame `df_resultados`. No entanto, o desvio padrão da Cross Validation (`cv_std_accuracy`) não foi armazenado neste DataFrame durante a etapa de avaliação inicial. Para gerar um gráfico preciso do desvio padrão, seria necessário reexecutar a etapa de avaliação e incluir essa métrica no DataFrame. Como a instrução era utilizar o DataFrame *criado anteriormente*, este gráfico específico não pode ser gerado no momento.

## 8. Interpretação Detalhada do Modelo Vencedor: LightGBM

### 8.1. Relatório de Classificação e Matriz de Confusão
"""

# Obter o melhor estimador LightGBM otimizado da lista de resultados otimizados
best_lightgbm_pipeline = None
for res in resultados_otimizados:
    if res['Modelo Otimizado'] == 'LightGBM':
        best_lightgbm_pipeline = res['Best Estimator']
        break

if best_lightgbm_pipeline is None:
    raise ValueError("Best LightGBM Estimator not found in resultados_otimizados. Please ensure the optimization cell (f52a9a84) has been executed and stores 'Best Estimator'.")

# Fazer previsões no conjunto de teste com o modelo otimizado
y_pred_optimized_lightgbm = best_lightgbm_pipeline.predict(X_test)

# Obter os nomes das classes originais para o relatório de classificação
class_names = le.inverse_transform(np.unique(y_test))

# 8.1.1. Relatório de Classificação
print("### Relatório de Classificação do LightGBM (Modelo Vencedor)\n")
print(classification_report(y_test, y_pred_optimized_lightgbm, target_names=class_names, zero_division=0))

# 8.1.2. Matriz de Confusão
print("\n### Matriz de Confusão do LightGBM (Modelo Vencedor)\n")
cm = confusion_matrix(y_test, y_pred_optimized_lightgbm)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('Matriz de Confusão do LightGBM Otimizado')
plt.xlabel('Predito')
plt.ylabel('Verdadeiro')
plt.show()

"""### 8.2. Feature Importance"""

# Obter o melhor estimador LightGBM otimizado da lista de resultados otimizados
best_lightgbm_pipeline = None
for res in resultados_otimizados:
    if res['Modelo Otimizado'] == 'LightGBM':
        best_lightgbm_pipeline = res['Best Estimator']
        break

if best_lightgbm_pipeline is None:
    raise ValueError("Best LightGBM Estimator not found in resultados_otimizados. Please ensure the optimization cell (f52a9a84) has been executed and stores 'Best Estimator'.")

# Obter o modelo LightGBM treinado dentro do pipeline
lightgbm_model = best_lightgbm_pipeline.named_steps['classifier']

# Obter a importância das features
feature_importances = lightgbm_model.feature_importances_

# Obter os nomes das features após o pré-processamento
# Isso é crucial porque o pré-processador transforma as features.
feature_names_out = best_lightgbm_pipeline.named_steps['preprocessor'].get_feature_names_out()

# Criar um DataFrame para visualização
df_feature_importances = pd.DataFrame({
    'Feature': feature_names_out,
    'Importance': feature_importances
}).sort_values(by='Importance', ascending=False)

print("### Importância das Features do LightGBM (Modelo Vencedor)\n")
display(df_feature_importances.head(15)) # Exibir as 15 features mais importantes

# Plotar a importância das features
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=df_feature_importances.head(15))
plt.title('Top 15 Importância das Features - LightGBM Otimizado')
plt.xlabel('Importância')
plt.ylabel('Feature')
plt.show()

"""### 8.3. Análise SHAP (SHapley Additive exPlanations)"""

import shap
import numpy as np
import matplotlib.pyplot as plt

# Check if 'resultados_otimizados' is defined, if not, raise an informative error.
if 'resultados_otimizados' not in globals() or resultados_otimizados is None:
    raise NameError("A variável 'resultados_otimizados' não está definida. Por favor, execute a célula 'f52a9a84' para otimizar os modelos e preencher esta variável.")

# Check if 'class_names' is defined, if not, raise an informative error.
if 'class_names' not in globals() or class_names is None:
    raise NameError("A variável 'class_names' não está definida. Por favor, execute a célula '42a672d3' para obter os nomes das classes.")

# Check if 'X_test' and 'y_test' are defined, if not, raise an informative error.
if 'X_test' not in globals() or 'y_test' not in globals():
    raise NameError("As variáveis 'X_test' e 'y_test' não estão definidas. Por favor, execute a célula '0e7c57f8' para carregar e dividir os dados.")

# Obter o melhor estimador LightGBM otimizado da lista de resultados otimizados
best_lightgbm_pipeline = None
for res in resultados_otimizados:
    if res['Modelo Otimizado'] == 'LightGBM':
        best_lightgbm_pipeline = res['Best Estimator']
        break

if best_lightgbm_pipeline is None:
    raise ValueError("Best LightGBM Estimator not found in resultados_otimizados. Please ensure the optimization cell (f52a9a84) has been executed and stores 'Best Estimator'.")

# Transformar os dados de X_test usando o pré-processador do pipeline
X_test_transformed = best_lightgbm_pipeline.named_steps['preprocessor'].transform(X_test)

# Criar um DataFrame para X_test_transformed com os nomes das features
feature_names_out = best_lightgbm_pipeline.named_steps['preprocessor'].get_feature_names_out()
X_test_transformed_df = pd.DataFrame(X_test_transformed, columns=feature_names_out)

# Criar um masker explícito para usar o conjunto de dados completo para perturbação interventional
# Isso evita o subsampling de 100 amostras do SHAP por padrão
masker = shap.maskers.Independent(data=X_test_transformed_df, max_samples=len(X_test_transformed_df))

# Criar um explainer SHAP para o modelo LightGBM, especificando model_output='probability'
# E feature_perturbation='interventional' para compatibilidade com model_output='probability'
# O argumento 'data' não é mais passado diretamente, mas sim o 'masker' configurado
explainer = shap.TreeExplainer(
    best_lightgbm_pipeline.named_steps['classifier'],
    data=masker,
    model_output="probability",
    feature_perturbation="interventional"
)

# Calcular os valores SHAP para o conjunto de teste
# Com model_output='probability', shap_values_3d será um array 3D: (n_samples, n_features, n_classes)
shap_values_3d = explainer.shap_values(X_test_transformed_df)

# 8.3.1. SHAP Summary Plot (Beeswarm) - Plotagem global simplificada
print("### SHAP Summary Plot (Beeswarm) do LightGBM (Modelo Vencedor)\n")
# shap.summary_plot funciona bem com um array 3D para multiclasse
shap.summary_plot(shap_values_3d, X_test_transformed_df, class_names=class_names, show=False)
plt.gcf().axes[-1].set_aspect('auto')
plt.gcf().axes[-1].set_box_aspect(1)
plt.show()

"""Executando as células predecessoras para definir as variáveis necessárias."""

# Executa o conteúdo da célula 0e7c57f8 para carregar e dividir os dados (X_test, y_test)
# e extrair o pré-processador.
get_ipython().run_cell_content("""
# 2.1. Leitura da base de dados
df = pd.read_csv('Obesity.csv')

# 2.2. Separação entre X (features) e y (target)
# Utilizando iloc para selecionar a última coluna como y e as demais como X,
# garantindo a robustez contra variações no nome da coluna alvo.
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Adicionando as importações necessárias diretamente aqui para garantir sua disponibilidade
from sklearn.model_selection import train_test_split
import numpy as np
import joblib # Adicionado para resolver o NameError

# 2.3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 2.4. Codificação da variável alvo (y) para numérico
# Alguns modelos, como o XGBoost, exigem rótulos numéricos para classificação multiclasse.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)
y_encoded = le.transform(y)

# Substituir y_train, y_test e y pelos seus equivalentes codificados
y_train = y_train_encoded
y_test = y_test_encoded
y = y_encoded

print("Dados carregados e separados em conjuntos de treino e teste.")
print(f"Shape de X_train: {X_train.shape}")
print(f"Shape de X_test: {X_test.shape}")
print(f"Shape de y_train: {y_train.shape}")
print(f"Shape de y_test: {y_test.shape}")
print(f"Classes originais: {le.inverse_transform(np.unique(y))}")
print(f"Classes codificadas: {np.unique(y)}")

# 2.5. Carregamento e Extração do Pré-processador do Pipeline Salvo
# O arquivo 'pipeline_obesity_final.pkl' deve estar disponível no ambiente.
pipeline_salvo = joblib.load("pipeline_obesity_final.pkl")

# Extrair apenas o pré-processador do pipeline
preprocessor = pipeline_salvo.named_steps["preprocessor"]

print("\nPipeline de pré-processamento 'pipeline_obesity_final.pkl' carregado com sucesso.")
print(f"Pré-processador extraído: {preprocessor}")
print("O pré-processador está pronto para ser aplicado aos dados sem novo treinamento.")
""")

# Executa o conteúdo da célula f52a9a84 para otimizar os modelos e definir 'resultados_otimizados'.
# Note: This cell has a lot of content, running it might take some time.
get_ipython().run_cell_content("""
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold # Adicionei StratifiedKFold
from scipy.stats import uniform, randint
from sklearn.pipeline import Pipeline

# Added imports for the classifiers used in this cell
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

# Added imports for metrics and time
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import time

# Lista para armazenar os resultados dos modelos otimizados
resultados_otimizados = []

# Definição do kf para o RandomizedSearchCV com cv=3
kf_optimized = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# Modelos finalistas com seus parâmetros a serem otimizados
# Note que 'classifier__' é prefixado para os parâmetros dentro do pipeline
modelos_finalistas_params = {
    'CatBoost': {
        'model': CatBoostClassifier(random_state=42, verbose=0, allow_writing_files=False),
        'param_distributions': {
            'classifier__iterations': randint(100, 250), # Ajustado para 100-250
            'classifier__learning_rate': uniform(0.01, 0.14), # Ajustado para 0.01-0.15 (0.15-0.01=0.14)
            'classifier__depth': randint(4, 8), # Ajustado para 4-8
            'classifier__l2_leaf_reg': uniform(2, 6) # Ajustado para 2-8 (8-2=6)
        }
    },
    'LightGBM': {
        'model': LGBMClassifier(random_state=42, verbose=-1),
        'param_distributions': {
            'classifier__n_estimators': randint(100, 250), # Ajustado para 100-250
            'classifier__learning_rate': uniform(0.01, 0.14), # Ajustado para 0.01-0.15
            'classifier__num_leaves': randint(20, 50), # Ajustado para 20-50
            'classifier__max_depth': randint(3, 12), # Ajustado para 3-12
            'classifier__reg_alpha': uniform(0, 1),
            'classifier__reg_lambda': uniform(0, 1)
        }
    },
    'XGBoost': {
        'model': XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss'),
        'param_distributions': {
            'classifier__n_estimators': randint(100, 250), # Ajustado para 100-250
            'classifier__learning_rate': uniform(0.01, 0.14), # Ajustado para 0.01-0.15
            'classifier__max_depth': randint(3, 8), # Ajustado para 3-8
            'classifier__subsample': uniform(0.70, 0.30), # Ajustado para 0.70-1.00 (1.00-0.70=0.30)
            'classifier__colsample_bytree': uniform(0.70, 0.30) # Ajustado para 0.70-1.00
        }
    }
}

for nome_modelo, config in modelos_finalistas_params.items():
    print(f"\nOtimizando o modelo: {nome_modelo}")

    # Criação do Pipeline com pré-processador e classificador
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', config['model'])
    ])

    # Configuração do RandomizedSearchCV
    random_search = RandomizedSearchCV(
        estimator=pipeline,
        param_distributions=config['param_distributions'],
        n_iter=10, # Número de iterações, ajustado conforme solicitado
        cv=kf_optimized, # Utilizando o kf_optimized com n_splits=3
        scoring='f1_macro',
        random_state=42,
        n_jobs=-1, # Utilizar todos os cores disponíveis
        verbose=2, # Verbose ajustado para 2
        refit=True # Refit ajustado para True
    )

    # Medir tempo de treinamento do RandomizedSearchCV
    start_time = time.time()
    random_search.fit(X_train, y_train)
    end_time = time.time()
    training_time_optimization = end_time - start_time

    best_estimator = random_search.best_estimator_
    best_params = random_search.best_params_
    best_score_cv = random_search.best_score_ # Obtendo o best_score_ diretamente

    print(f"  Melhores parâmetros para {nome_modelo}: {best_params}")
    print(f"  Melhor F1 Macro (CV) para {nome_modelo}: {best_score_cv:.4f}")
    print(f"  Tempo de otimização para {nome_modelo}: {training_time_optimization:.2f} segundos")

    # Calcular métricas com o melhor estimador no conjunto de teste
    y_pred_optimized = best_estimator.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred_optimized)
    precision_macro = precision_score(y_test, y_pred_optimized, average='macro', zero_division=0)
    recall_macro = recall_score(y_test, y_pred_optimized, average='macro', zero_division=0)
    f1_macro = f1_score(y_test, y_pred_optimized, average='macro', zero_division=0)

    # Armazenar resultados otimizados
    resultados_otimizados.append({
        'Modelo Otimizado': nome_modelo,
        'Melhores Parâmetros': best_params,
        'Acurácia': accuracy,
        'Precisão Macro': precision_macro,
        'Recall Macro': recall_macro,
        'F1 Macro': f1_macro,
        'Best CV Score': best_score_cv, # Usando best_score_ diretamente
        'Tempo de Otimização (s)': training_time_optimization,
        'Best Estimator': best_estimator # Adicionando o best_estimator_ aqui
    })

    print(f"  Acurácia (Otimizado - Teste): {accuracy:.4f}")
    print(f"  Precisão Macro (Otimizado - Teste): {precision_macro:.4f}")
    print(f"  Recall Macro (Otimizado - Teste): {recall_macro:.4f}")
    print(f"  F1 Macro (Otimizado - Teste): {f1_macro:.4f}")
""")

# Executa o conteúdo da célula 42a672d3 para definir 'class_names' e exibir relatório/matriz de confusão.
# Apenas a parte que define class_names é estritamente necessária para a célula 78565d2d,
# mas executaremos a célula completa para manter a consistência do notebook.
get_ipython().run_cell_content("""
# Obter o melhor estimador LightGBM otimizado da lista de resultados otimizados
best_lightgbm_pipeline = None
for res in resultados_otimizados:
    if res['Modelo Otimizado'] == 'LightGBM':
        best_lightgbm_pipeline = res['Best Estimator']
        break

if best_lightgbm_pipeline is None:
    raise ValueError("Best LightGBM Estimator not found in resultados_otimizados. Please ensure the optimization cell (f52a9a84) has been executed and stores 'Best Estimator'.")

# Fazer previsões no conjunto de teste com o modelo otimizado
y_pred_optimized_lightgbm = best_lightgbm_pipeline.predict(X_test)

# Obter os nomes das classes originais para o relatório de classificação
# 'le' (LabelEncoder) é definido na célula 0e7c57f8
class_names = le.inverse_transform(np.unique(y_test))

# 8.1.1. Relatório de Classificação
print("### Relatório de Classificação do LightGBM (Modelo Vencedor)\n")
print(classification_report(y_test, y_pred_optimized_lightgbm, target_names=class_names, zero_division=0))

# 8.1.2. Matriz de Confusão
print("\n### Matriz de Confusão do LightGBM (Modelo Vencedor)\n")
cm = confusion_matrix(y_test, y_pred_optimized_lightgbm)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('Matriz de Confusão do LightGBM Otimizado')
plt.xlabel('Predito')
plt.ylabel('Verdadeiro')
plt.show()
""")

"""As células predecessoras foram executadas. Agora, por favor, execute a célula `78565d2d` novamente para gerar o SHAP Summary Plot.

### 8.4. Análise Técnica dos Resultados

#### Quais variáveis mais influenciaram?

Baseado na **Importância das Features** e nos **SHAP Plots** do LightGBM, as variáveis que mais influenciaram na predição da obesidade foram:

*   **`Weight` (Peso):** Consistentemente a feature mais importante, o que é esperado em um problema de classificação de obesidade. Variações no peso têm um impacto direto e significativo na determinação da classe de obesidade.
*   **`Height` (Altura):** Também de alta relevância, trabalhando em conjunto com o peso para definir o Índice de Massa Corporal (IMC), que é um fator crucial na classificação da obesidade.
*   **`Age` (Idade):** Apresentou uma influência considerável, sugerindo que a idade é um fator importante na propensão ou manifestação de diferentes tipos de obesidade.
*   **`FCVC` (Frequência de Consumo de Vegetais):** Embora seja uma feature relacionada ao hábito alimentar, sua presença entre as top features mostra que a dieta desempenha um papel importante.
*   **`NCP` (Número de Refeições Principais):** Outro hábito alimentar que contribui significativamente, indicando que a frequência alimentar é relevante.

Os **SHAP Summary Plots** confirmam essa hierarquia, mostrando que `Weight`, `Height`, `Age`, `FCVC` e `NCP` são as características com maior magnitude SHAP (impacto médio absoluto) nas previsões do modelo.

#### Quais classes apresentaram maior dificuldade?

Analisando o **Relatório de Classificação** e a **Matriz de Confusão**:

*   **Classes com menor F1-Score (ou menor Recall/Precision)** tendem a ser as mais difíceis de classificar. Em geral, é comum que classes com menos exemplos no conjunto de dados (classes minoritárias) ou classes com características muito semelhantes a outras (sobreposição de features) apresentem maior dificuldade.
*   Pela Matriz de Confusão, observe as células fora da diagonal principal. Valores mais altos nessas células indicam que o modelo está confundindo uma classe com outra. Por exemplo, se há muitos casos de 'Obesity_Type_I' sendo preditos como 'Normal_Weight' ou vice-versa, isso indica uma dificuldade de distinção entre essas classes.
*   É possível que classes adjacentes no espectro da obesidade (e.g., `Overweight_Level_I` e `Overweight_Level_II`, ou `Obesity_Type_I` e `Normal_Weight`) sejam as mais desafiadoras de diferenciar devido à similaridade de seus perfis de características, resultando em mais erros de classificação entre elas.

#### Como interpretar os resultados?

*   **Relatório de Classificação:** Fornece métricas de precisão, recall e F1-score para cada classe. Um F1-score alto para uma classe indica que o modelo é bom tanto em identificar corretamente instâncias dessa classe (alta precisão) quanto em encontrar todas as instâncias dessa classe (alto recall).
*   **Matriz de Confusão:** Visualiza o desempenho do modelo em detalhes. A diagonal principal mostra as previsões corretas para cada classe. Fora da diagonal, vemos os erros de classificação. Uma célula `(i, j)` fora da diagonal indica que `i` instâncias da classe verdadeira foram preditas erroneamente como classe `j`. Isso ajuda a identificar quais classes são confundidas.
*   **Feature Importance:** No LightGBM, a importância das features é baseada na frequência com que uma feature é usada em divisões nas árvores ou no ganho total de informação que ela proporciona. Valores mais altos indicam maior influência.
*   **SHAP (SHapley Additive exPlanations):**
    *   **SHAP Summary Plot (Beeswarm):** Cada ponto no gráfico representa uma instância no conjunto de dados. A posição horizontal do ponto mostra o valor SHAP para essa feature naquela instância. A cor indica o valor da feature (vermelho = alto, azul = baixo). Isso nos permite ver a distribuição do impacto de uma feature em todas as previsões. Por exemplo, se valores altos de 'Weight' (vermelho) movem o valor SHAP para a direita, significa que um peso alto tende a aumentar a predição para uma determinada classe de obesidade. Se o `shap_values` é uma lista para classes, cada plot individual é para uma classe específica.
    *   **SHAP Bar Plot:** Mostra a média do valor absoluto SHAP para cada feature, indicando a importância geral da feature em termos de sua contribuição para a magnitude da predição. Para modelos multiclasse, você pode ter um Bar Plot por classe, mostrando quais features são mais importantes para prever *aquela classe específica*.
"""